### ISSUE TITLE
Faire la fenêtre visualiser le planning

### ISSUE THREAD

**Issue by labriquerie2019** [labriquerie2019/medicaltrack#10]
Faire la fenêtre visualiser le planning
La fenêtre permettra de visualiser les opérations à venir et celle qui se déroule actuellement.

Reprendre le code de l'application de l'afficheur au dessus des salles d'opérations ?
Ou refaire une frame différentes avec l'affichage couper en deux, et voir le planning des deux salles?

**Comment by Orange57** [comment]
Finis
